name: Sync

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@main
        with:
          go-version: stable

      - name: Install tool
        env:
          GOPROXY: direct
        run: |
          go install github.com/mix-mirror/reposync/cmd/reposync@latest

      - name: Sync
        continue-on-error: true
        id: sync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cp profile/README.tpl.md profile/README.md
          reposync -config config.yml -markdown profile/README.md

      - name: Commit
        run: |
          set -xve
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sync with origin at $(date -u +%Y-%m-%dT%H:%M:%SZ) [skip ci]"
            git push
          fi
